[workspace]
members = ["attribute", "common", "derive", "parse", "function"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
macrotest = "1.2.1"
trybuild = "1.0.116"
proc-macro-crate = "3.5.0"
proc-macro2 = { version = "1.0.106", features = ["span-locations"] }
quote = "1.0.45"
sealed = "0.7.0"
syn = { version = "3.0.2", features = ["derive", "full", "extra-traits"] }
pa = { version = "1.4.1", package = "pretty_assertions" }
rstest = "0.26.1"
convert_case = "0.11.0"

[package]
name = "proc"
version.workspace = true
edition.workspace = true

[dependencies]
proc_attribute = { path = "attribute" }
proc_derive = { path = "derive" }
proc_parse = { path = "parse" }
proc_common = { path = "common" }
proc_function = { path = "function" }
