[workspace]
resolver = "3"
members = ["proc", "attribute", "common", "derive", "parse", "function"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
macrotest = "1.2.1"
trybuild = "1.0.121"
proc-macro-crate = "3.5.0"
sealed = "0.7.0"
syn = { version = "3.0.2", features = ["derive", "full", "extra-traits"] }
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
quote = "1.0.47"
pa = { version = "1.4.1", package = "pretty_assertions" }
rstest = "0.27.0"
convert_case = "0.12.0"