[package]
name = "proc_derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc_attribute = { path = "../attribute" }
proc_common = { path = "../common" }
convert_case.workspace = true

[dev-dependencies]
macrotest.workspace = true
trybuild.workspace = true
