use proc_macro2::TokenStream;
use quote::{quote, ToTokens};
use syn::{Ident, Type, Variant};

use super::{standard_ident, ForEachField};

/// Generate code for an enum variant given tokens for each of its fields (if
/// any)
///
/// The [`ToTokens`] implementation generates `Variant { field: expr, ... }`,
/// `Variant ( expr, ...)` or `Variant` for struct, tuple and unit variants
/// respectively. Where `expr` is generated by invoking the passed closure. Note
/// it does not generate the enum name itself. Callers are responsible for
/// placing `Self` or the enum name as appropriate.
///
/// The first argument to the supplied closure is the actual name of each field
/// for struct variants and an [`Ident`] of the form `_<idx>` for tuple
/// variants. These choices are guarenteed to match [`EnumMatcher`]
///
/// In both cases the tokens returned from the closure are used for
/// the value of the field in both places. For struct variants the `ident: `
/// prefix is supplied automatically.
#[expect(missing_debug_implementations)]
pub struct VariantExpander<'a, F: Fn(&Ident, &Type) -> TokenStream>(
    pub &'a Variant,
    pub F,
);

impl<F: Fn(&Ident, &Type) -> TokenStream> ToTokens for VariantExpander<'_, F> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.0.ident.to_tokens(tokens);
        ForEachField(&self.0.fields, |idx, field| {
            let ident = standard_ident(&idx, field);
            let expr = (self.1)(&ident, &field.ty);
            if field.ident.is_some() {
                quote!(#ident: #expr)
            } else {
                quote!(#expr)
            }
        })
        .to_tokens(tokens);
    }
}

/// Generate an appropriate match clause for an enum variant.
///
/// The [`ToTokens`] implementation genrates `Variant { field, ... }`,
/// `Variant ( _<idx>, ... )` or `Variant` for struct, tuple and unit variants
/// respectivley. As with [`VariantExpander`] the caller must supply the
/// `Self`/the variant name manually. The names chosen for the fields in the
/// match clauses of struct and tuple enums are guarenteed to match
/// [`VariantExpander`].
#[expect(missing_debug_implementations)]
pub struct EnumMatcher<'a>(pub &'a Variant);

impl ToTokens for EnumMatcher<'_> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.0.ident.to_tokens(tokens);
        ForEachField(&self.0.fields, |idx, field| {
            standard_ident(&idx, field).into_token_stream()
        })
        .to_tokens(tokens);
    }
}

#[cfg(test)]
mod tests {
    use pa::assert_eq;
    use quote::{quote, ToTokens};
    use syn::ItemEnum;

    use super::{EnumMatcher, VariantExpander};

    #[test]
    fn variant_expander() {
        let item: ItemEnum = syn::parse_quote! {
            enum MyEnum {
                Unit,
                Tuple(usize, String),
                Named { first: usize, second: String },
            }
        };
        let mut results = item.variants.iter().map(|v| {
            VariantExpander(v, |ident, ty| quote!([ident: #ident][ty: #ty]))
        });
        let (unit, tuple, named) = (
            results.next().unwrap(),
            results.next().unwrap(),
            results.next().unwrap(),
        );
        assert_eq!("Unit", unit.into_token_stream().to_string());
        assert_eq!(
            "Tuple ([ident : _0] [ty : usize] , [ident : _1] [ty : String])",
            tuple.into_token_stream().to_string()
        );
        assert_eq!(
            "Named { first : [ident : first] [ty : usize] , second : [ident : second] [ty : String] }",
            named.into_token_stream().to_string()
        );
    }

    #[test]
    fn enum_matcher() {
        let item: ItemEnum = syn::parse_quote! {
            enum MyEnum {
                Unit,
                Tuple(usize, String),
                Named { first: usize, second: String },
            }
        };
        let mut results = item.variants.iter().map(EnumMatcher);
        let (unit, tuple, named) = (
            results.next().unwrap(),
            results.next().unwrap(),
            results.next().unwrap(),
        );
        assert_eq!("Unit", unit.into_token_stream().to_string());
        assert_eq!("Tuple (_0 , _1)", tuple.into_token_stream().to_string());
        assert_eq!(
            "Named { first , second }",
            named.into_token_stream().to_string()
        );
    }
}
