name: Merge Dependabot PRs
# on:
#   schedule:
#     - cron: "0 0 * * *"
on: workflow_dispatch
  
env:
    GH_TOKEN: ${{ github.token }}

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Pick PR
        run: gh pr list --json url,author,statusCheckRollup | jq -r '[.[] | select(.author.login == "app/dependabot") | select(all(.statusCheckRollup[]; .conclusion == "SUCCESS")) | .url][0]'
